### ISSUE TITLE
`new Buffer` should be replaced with `Buffer.from`

### ISSUE THREAD

**Issue by evanpurkhiser** [dimerica-industries/node-cursor#1]
```
(node:80503) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:174:11)
    at new Buffer (buffer.js:257:3)
    at Cursor (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/cursor/index.js:10:1)
    at new Cursor (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/js-xdr/lib/cursor.js:30:1)
    at Function.toXDR (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/js-xdr/lib/io-mixin.js:25:1)
    at ChildStruct.toXDR (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/js-xdr/lib/io-mixin.js:63:1)
    at Object.makeProgramClient (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:4978:1)
    at getClients (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:4850:1)
    at Object.fetchFile (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:4908:37)
    at fetchPdbData (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:1158:1)
    at LocalDatabase.<anonymous> (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:1174:1)
    at /Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/prolink-connect/lib/index.js:1228:59
    at /Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/async-mutex/es6/Mutex.js:21:58
    at Semaphore.<anonymous> (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/async-mutex/es6/Semaphore.js:29:1)
    at step (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/tslib/tslib.es6.js:100:1)
    at Object.next (/Users/evan/Coding/personal/prolink-tools/dist/webpack:/node_modules/tslib/tslib.es6.js:81:45)

```

See https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

**Comment by evanpurkhiser** [comment]
Bump @dougnukem @jonasi. I can open a PR for this.
